### ISSUE TITLE
How to use this without getting "Ambiguous use of 'init..." compilation error?

### ISSUE THREAD

**Issue by longseespace** [david-swift/ColibriComponents-macOS#1]
I got a lot of compilation errors like this: `Ambiguous use of 'init(_:selection:content:)'`

My code:

```
Picker("", selection: $model) {
    ForEach(gptModels, id: \.self) {
        Text($0)
    }
}
```

How can you use it? @david-swift

**Comment by david-swift** [comment]
> **Note**
> This comment shows solutions when using ColibriComponents **0.1.6 or older**. 
> For version **0.1.7 and later**, read [this comment](https://github.com/david-swift/ColibriComponents-macOS/issues/1#issuecomment-1627433020).
## :wrench: Quick Fixes
I'm not sure whether `""` in your example should be a `LocalizedStringResource` or a `String` (or any other type that can be initialized using a string literal), so here are solutions for both cases.

### `""` is a `LocalizedStringResource`

I'm using the [`LocalizedStringResource`](https://developer.apple.com/documentation/foundation/localizedstringresource/) initializer with a comment like that:
```swift
Picker(.init("Label", comment: "Information for the localization"), selection: $model) {
    ForEach(gptModels, id: \.self) {
        Text($0)
    }
}
```

In order to make things faster, I have created a code snippet in Xcode (`Editor > Create Code Snippet...`) for localized string resources:
```
.init("<#Label#>", comment: "<#File#> (<#Comment#>)")
```

There is currently no "beautiful" way for adding a localized string resource without a comment.

### `""` is a `String` or another type

As I personally never use string literals or `LocalizedStringKey` directly in the UI definition, I haven't really thought about that. 

Here are some possible solutions. Replace `String` with the type you need.
```swift
Picker("" as String, selection: $model) {
    ForEach(gptModels, id: \.self) {
        Text($0)
    }
}
```
```swift
Picker(String(""), selection: $model) {
    ForEach(gptModels, id: \.self) {
        Text($0)
    }
}
```
```swift
let pickerLabel: String = ""
Picker(pickerLabel, selection: $model) {
    ForEach(gptModels, id: \.self) {
        Text($0)
    }
}
```

## :bird: Changes in the Library

ColibriComponents currently isn't suited for being added to a project that uses string literals in the UI. Maybe it would make more sense to add `StringProtocol` conformance to the `LocalizedStringResource` instead of adding initializers to important SwiftUI views. I think that would not only resolve that issue, but would make more sense overall.

> **Note**
> Upgrade to ColibriComponents **0.1.7** to get those changes.
> Read [this comment](https://github.com/david-swift/ColibriComponents-macOS/issues/1#issuecomment-1627433020) for more information.

What do you think about that, @longseespace? Thank you very much for this issue!

**Comment by david-swift** [comment]
# New in [ColibriComponents 0.1.7](https://github.com/david-swift/ColibriComponents-macOS/releases/tag/0.1.7)

If `""` should be a `LocalizedStringKey`, use:
```swift
Picker("", selection: $model) {
    ForEach(gptModels, id: \.self) {
        Text($0)
    }
}
```
This should not throw the `Ambiguous use of 'init(_:selection:content:)'` error.

If `""` should be a `LocalizedStringResource`, use:
```swift
Picker(.init("", comment: "Information for the localization"), selection: $model) {
    ForEach(gptModels, id: \.self) {
        Text($0)
    }
}
```

Because of those changes, it should now be possible to add ColibriComponents to a project without having to change the project's code.

Does updating to version 0.1.7 solve your problem, @longseespace?

**Comment by longseespace** [comment]
That's perfect. Actually I was running into this issue while using your other library `SettingsKit`. Can you update the dependencies there also. Thanks a lot 🙏

**Comment by david-swift** [comment]
Yes, I'll update the dependencies. Thank you very much for opening this issue!
